import type { Metadata } from "next";
import { Inter } from "next/font/google"; // 1. Импортируем 'Inter'
import "./globals.css";

// 2. Настраиваем 'Inter'
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // 3. Применяем 'inter.className' вместо 'GeistMono.className'
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}